# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Step 09 LEC Polylines to Polygon by Contour.py
# Created on: 2020-04-20 20:40:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Step 09 LEC Polylines to Polygon by Contour <Input_Contour_lines> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
Input_Contour_lines = arcpy.GetParameterAsText(0)

# Local variables:
Data = Input_Contour_lines
Path = "FILE"
Value = "1"
output_1 = "%Path%\\%Name%_polygon_temp_%Value%.shp"
alter_1 = output_1
alter_2 = alter_1
Name = "FILE"

# Process: Parse Path
arcpy.ParsePath_mb(Input_Contour_lines, "PATH")

# Process: Iterate Feature Selection
arcpy.IterateFeatureSelection_mb(Input_Contour_lines, "CONTOUR #", "false")

# Process: Feature To Polygon
tempEnvironment0 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Same As Input"
arcpy.FeatureToPolygon_management("''", output_1, "", "NO_ATTRIBUTES", "")
arcpy.env.outputMFlag = tempEnvironment0

# Process: Add Field
arcpy.AddField_management(output_1, "Contour", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(alter_1, "Contour", "%Value%", "VB", "")

# Process: Parse Name
arcpy.ParsePath_mb(Input_Contour_lines, "NAME")

